Repository PMEAL/OpenPNM, pull requests merged in 2018-09, with the labels that each got.

#1095 Subclass get
  openpnm/core/Base.py
  tests/unit/core/BaseTest.py
Labels: Priority - Low, enhancement

#1093 Outflow boundary condition for AdvectionDiffusion/Dispersion
  conda_requirements.txt
  example_script.py
  openpnm/algorithms/AdvectionDiffusion.py
  openpnm/algorithms/Dispersion.py
  openpnm/algorithms/GenericTransport.py
  openpnm/algorithms/TransientDispersion.py
  openpnm/algorithms/__init__.py
  openpnm/topotools/topotools.py
  openpnm/utils/petsc.py
  requirements.txt
  tests/unit/algorithms/AdvectionDiffusionTest.py
  tests/unit/algorithms/DispersionTest.py
  tests/unit/algorithms/HybridAdvectionDiffusionTest.py
  tests/unit/algorithms/PowerlawAdvectionDiffusionTest.py
  tests/unit/algorithms/SolversTest.py
  tests/unit/algorithms/SubclassedTransportTest.py
  tests/unit/algorithms/TransientDispersionTest.py
  tests/unit/algorithms/UpwindAdvectionDiffusionTest.py
  tests/unit/utils/UtilsTest.py
Labels: Next Minor Release, Priority - High, enhancement

#1091 Add bidirectional touch pressure models
  openpnm/algorithms/MixedInvasionPercolation.py
  openpnm/models/physics/capillary_pressure.py
  openpnm/models/physics/meniscus.py
  tests/unit/algorithms/MixedPercolationTest.py
  tests/unit/models/physics/CapillaryPressureTest.py
  tests/unit/models/physics/MeniscusTest.py
Labels: Next Minor Release, enhancement

#1104 Improve merge_pores to be able to merge list of lists of pores
  openpnm/topotools/topotools.py
  setup.cfg
  tests/unit/topotools/TopotoolsTest.py
Labels: Next Minor Release, Performance
