Repository PMEAL/OpenPNM, pull requests merged in 2019-04, with the labels that each got.

#1232 Add "Returns" section to pore-scale models, where missing
  example_PNP.py
  openpnm/models/geometry/pore_area.py
  openpnm/models/geometry/pore_seed.py
  openpnm/models/geometry/pore_size.py
  openpnm/models/geometry/pore_surface_area.py
  openpnm/models/geometry/pore_volume.py
  openpnm/models/geometry/throat_area.py
  openpnm/models/geometry/throat_centroid.py
  openpnm/models/geometry/throat_endpoints.py
  openpnm/models/geometry/throat_length.py
  openpnm/models/geometry/throat_perimeter.py
  openpnm/models/geometry/throat_shape_factor.py
  openpnm/models/geometry/throat_size.py
  openpnm/models/geometry/throat_surface_area.py
  openpnm/models/geometry/throat_vector.py
  openpnm/models/geometry/throat_volume.py
  openpnm/models/misc/basic_math.py
  openpnm/models/misc/neighbor_lookups.py
  openpnm/models/misc/simple_equations.py
  openpnm/models/misc/statistical_distributions.py
  openpnm/models/phases/density.py
  openpnm/models/phases/diffusivity.py
  openpnm/models/phases/electrical_conductivity.py
  openpnm/models/phases/molar_density.py
  openpnm/models/phases/surface_tension.py
  openpnm/models/phases/thermal_conductivity.py
  openpnm/models/phases/vapor_pressure.py
  openpnm/models/phases/viscosity.py
  openpnm/models/physics/capillary_pressure.py
  openpnm/models/physics/multiphase.py
Labels: documentation

#1234 classic pore scale model addition
  openpnm/models/physics/diffusive_conductance.py
  openpnm/models/physics/hydraulic_conductance.py
  openpnm/physics/Classic.py
  openpnm/physics/__init__.py
  tests/unit/models/physics/DiffusiveConductanceTest.py
  tests/unit/models/physics/HydraulicConductanceTest.py
Labels: enhancement

#1254 removing bug from test valvatne model.
  tests/unit/models/physics/HydraulicConductanceTest.py
Labels: bug
