Repository PMEAL/OpenPNM, pull requests merged in 2020-08, with the labels that each got.

#1616 Replace pep8 w/ pycodestyle
  .github/workflows/ci-macos.yml
  .github/workflows/ci-min.yml
  .github/workflows/ci-ubuntu.yml
  .github/workflows/ci-windows.yml
  openpnm/topotools/topotools.py
  requirements/test_requirements.txt
  tests/unit/algorithms/MultiphysicsNernstPlanckSolverTest.py
  tests/unit/algorithms/TransientMultiphysicsNernstPlanckSolverTest.py
  tests/unit/models/geometry/PoreVolumeTest.py
Labels: bug, high priority, maintenance

#1614 Migrate from pip to conda in CI workflows
  .github/workflows/ci-macos.yml
  .github/workflows/ci-min.yml
  .github/workflows/ci-ubuntu.yml
  .github/workflows/ci-windows.yml
  .github/workflows/examples.yml
  .github/workflows/release-notes.yml
  openpnm/topotools/topotools.py
  requirements/conda_requirements.txt
  requirements/test_requirements.txt
  tests/unit/models/physics/FlowShapeFactorsTest.py
  tests/unit/models/physics/PoissonShapeFactorsTest.py
Labels: enhancement, high priority

#1538 Metrics finalize
  openpnm/algorithms/__init__.py
  openpnm/algorithms/metrics/RelativePermeability.py
  tests/unit/algorithms/metrics/RelativePermabilityTest.py
Labels: enhancement, high priority

#1617 Better default solver
  .github/workflows/ci-macos.yml
  .github/workflows/ci-min.yml
  .github/workflows/ci-ubuntu.yml
  .github/workflows/ci-windows.yml
  .github/workflows/examples.yml
  README.md
  examples/extractions/Working with Extracted Networks.ipynb
  examples/extractions/benchmarks/Benthemeir.ipynb
  examples/extractions/benchmarks/Berea.ipynb
  examples/extractions/benchmarks/Doddington.ipynb
  examples/io_and_visualization/Quick Plotting in OpenPNM.ipynb
  examples/paper_recreations/Gostick et al. (2007)/Gostick et al. (2007).ipynb
  examples/paper_recreations/Tranter et al. (2017)/Tranter et al. (2017) - Part A.ipynb
  examples/paper_recreations/Tranter et al. (2017)/Tranter et al. (2017) - Part B.ipynb
  examples/paper_recreations/Tranter et al. (2017)/Tranter et al. (2017) - Part C.ipynb
  examples/percolation/Part A - Ordinary Percolation.ipynb
  examples/percolation/Part B - Invasion Percolation.ipynb
  examples/percolation/Part C - Mixed Invasion Percolation.ipynb
  examples/percolation/Part D - Meniscus Model Comparison.ipynb
  examples/simulations/Advection-Diffusion.ipynb
  examples/simulations/Capillary Pressure Curves.ipynb
  examples/simulations/Fickian Diffusion.ipynb
  examples/simulations/Match Analytical Temperature Profile.ipynb
  examples/simulations/Relative Diffusivity.ipynb
  examples/simulations/Relative Permeability in 2D.ipynb
  examples/simulations/Transient Fickian Diffusion.ipynb
  examples/simulations/Working with Source and Sink Terms.ipynb
  examples/topology/Adding Boundary Pores.ipynb
  examples/topology/Generate Dual Cubic Lattice.ipynb
  examples/topology/Stitching Networks Together.ipynb
  examples/topology/Topology Extension.ipynb
  examples/topology/Using Queries - Level 1.ipynb
  examples/topology/Various Cubic Networks.ipynb
  examples/topology/Voronoi Fibers.ipynb
  examples/tutorials/Heat Transfer (1D).ipynb
  examples/tutorials/Heat Transfer with Source Term (1D).ipynb
  examples/tutorials/Intro to OpenPNM - Advanced.ipynb
  examples/tutorials/Using Workspace and Projects.ipynb
  openpnm/algorithms/GenericTransport.py
  openpnm/algorithms/ReactiveTransport.py
  pytest.ini
  requirements/.condarc
  tests/environment.yml
  tests/unit/algorithms/SubclassedTransportTest.py
Labels: enhancement, high priority, maintenance
