Repository PMEAL/OpenPNM, pull requests merged in 2020-07, with the labels that each got.

#1551 Automatically create release notes when deploying to PyPI
  .github/workflows/logger.sh
  .github/workflows/publish-to-pypi.yml
  .github/workflows/release-notes.yml
Labels: Enhancement, Priority - Low

#1560 Prevent connectivity = 8 or 12 in Cubic networks
  examples/tutorials/Intro to OpenPNM - Intermediate.ipynb
  openpnm/network/Cubic.py
  tests/unit/network/CubicTest.py
Labels: Enhancement, Priority - Medium

#1555 Enhance GenericTransport's sanity check method
  openpnm/algorithms/GenericTransport.py
  openpnm/models/physics/flow_shape_factors.py
  openpnm/models/physics/poisson_shape_factors.py
  openpnm/network/GenericNetwork.py
  tests/unit/algorithms/GenericTransportTest.py
  tests/unit/network/GenericNetworkTest.py
Labels: enhancement, high priority

#1576 Significant change to datatype conversion in interleave_data
  openpnm/core/Base.py
  tests/unit/core/BaseTest.py
  tests/unit/core/SubdomainTest.py
  tests/unit/models/physics/DiffusiveConductanceTest.py
Labels: bug, high priority

#1590 Effective volume
  examples/simulations/Transient Fickian Diffusion.ipynb
  openpnm/algorithms/TransientReactiveTransport.py
  openpnm/models/geometry/pore_volume.py
  tests/unit/models/geometry/PoreVolumeTest.py
Labels: enhancement, good first issue
